### ISSUE TITLE
Dead link on https://github.com/ptcrealitylab/vuforia-spatial-toolbox-documentation/blob/2e01ed03aa4f585ca05d702d645bff307be46136/use/README.md

### ISSUE THREAD

**Issue by alexshill** [ptcrealitylab/vuforia-spatial-toolbox-documentation#64]
At the bottom of https://github.com/ptcrealitylab/vuforia-spatial-toolbox-documentation/blob/2e01ed03aa4f585ca05d702d645bff307be46136/use/README.md there is a link to Using the App which is dead

**Comment by alexshill** [comment]
Same here https://github.com/ptcrealitylab/vuforia-spatial-toolbox-documentation/tree/2e01ed03aa4f585ca05d702d645bff307be46136/use/spatial-programming

**Comment by hobinjk-ptc** [comment]
Thanks for the report! Unfortunately it's not currently possible to have the same links work on https://spatialtoolbox.vuforia.com/ and the GitHub view of the raw markdown files
